### PR TITLE
Add support for Ubuntu Xenial builds

### LINKED ISSUE #3: Add support for Xenial
Placeholder issue to link to from the TODO being added by travis-ci/packer-templates#549.

### PR DESCRIPTION
**Pull request by edmorley**
Another step in trying to green up the Xenial opal image.

Fixes #3.

### CODE REVIEW

**Comment by edmorley** [comment]
Surprisingly the build seems to work with no other changes required :-)
https://travis-ci.org/travis-ci/perl-builder/jobs/301097058

**Comment by BanzaiMan** [comment]
Maybe I did something right.

**Comment by edmorley** [comment]
@BanzaiMan, thank you for merging - I don't suppose you could trigger builds for:
VERSION=5.22.4 ALIAS=5.22
VERSION=5.24.3 ALIAS=5.24

(To correspond with: https://github.com/travis-ci/packer-templates/blob/24903bd0c0a6bc76b6a0b9dec74015fdbd181739/cookbooks/travis_ci_opal/attributes/default.rb#L14-L21)

**Comment by edmorley** [comment]
> Maybe I did something right.

I don't know if my comment above came across the wrong way or not, but in case so - I meant "surprisingly" as in the "it still works even on the minimal image variant that I had to use because the others don't yet exist" sense, rather than as a criticism of the script at all :-)

**Comment by edmorley** [comment]
> I don't suppose you could trigger builds for:

Many thanks :-)

https://travis-ci.org/travis-ci/perl-builder/jobs/301926107
https://travis-ci.org/travis-ci/perl-builder/jobs/301926167

**Pull request merged**
